### PR TITLE
Migration to bootstrap3. Fixes #30

### LINKED ISSUE #30: Replace Angular Material with Another Library
Angular Material is not working correctly (specially in selects), so will replace it with another frontend library.

### PR DESCRIPTION
**Pull request by AxelCB**
Finished migrating to bootstrap 3 (branch has wrong name).

Please checkout this branch and check if everything it's okay

### CODE REVIEW

**Comment by AxelCB** [comment]
Now requires to erase node_modules folder and re-run npm install

**Comment by mokocchi** [comment]
I took a challenge No.1 without nextChallenge. Then I set nextChallenge to challenge No.2. It was OK.
But when I set it back to "none", it seems it's sending an empty object (not null). Maybe it's the same as the empty hint issue we had before... If Angular can't send nulls then the backend should solve the issue (If that's the case I'll do it)

**Comment by AxelCB** [comment]
Right... the frontend is actually sending an empty object ( I mapped it that way in the select). Thought it was better that way and that it was considered a possible value in the backend. I'll add an if to send null if "None" option was selected since it seems more rational.

**Comment by AxelCB** [comment]
Updated this to fix the "null/empty object" situation.

Also, didn't notice before, but when you review a pull request you can send a response requesting more changes instead of just commenting here

**Review by mokocchi — APPROVED** [review]
Now it's ok to merge. The problems were solved.

**Pull request merged**
