### PR TITLE
File Upload feature for challenges. Fixes #12

### LINKED ISSUE #12: file upload for challenges
[This spring tutorial](https://spring.io/guides/gs/uploading-files/) may help.  
We could create a challenge, then upload the file to /challenges/{id}/file with PUT.  
That way the URI would be stored in the challenge without further requests.  
I'm not sure what kind of security checks should we do, since it's a CTF app...

### PR DESCRIPTION
**Pull request by AxelCB**
Haven't tested it thoroughly.

There may be certain bugs like, say you uploaded same filename in two challenges ( doesn't matter if it's really the same file, just the name). The second challenge overwrites the first uploaded file. Also, if you later decided to change or remove that file in any of those challenges, the other one would still have the reference to the file but it would be deleted, so it would probably crash...

### CODE REVIEW

**Comment by AxelCB** [comment]
Reviewed the merging conflicts from the github browser option...may need re-checking to see if everything's working.

**Review by mokocchi — CHANGES_REQUESTED** [review]
Well, here I have the review:

1) Delete is not working. Through debug I noticed that `remove(filename)` method at `StorageServiceFileSystemImpl` class (line 54 I think) recieves a full path, and then adds the directory path again. Removing everything but the filename from the variable with the debug editor solved the problem for me, so tracking where is this value stored should solve the issue.

2) The url variable of Challenge class should be a server-relative url so other modules can get the file directly (currently it shows a path relative to my local filesystem). Maybe the `store(file)` method at `StorageServiceFileSystemImpl` class could return only the filename (without the rest of the path) to the controller. I'm not sure what the controller part does afterwards but my guess is that creates the server-relative url we want, right? Something like `localhost:8080/api/challenges/files/c6dbfcb57e1526c592816abd77c5dc62`

3) About the filename issue: 
How about adding the date/time to the hashes to avoid collisions? Something like
```java
String date = new SimpleDateFormat("dd/MM/yyyy-hhmmss.SSS").format(new Date());
stringToHash += date;
```

**Comment by AxelCB** [comment]
I'm currently working on fixing 1) and 2).

Regarding 3) ,it's not possible to add de date/time to avoid collisions, since in some services (I don't remember exactly which, would need to check first) we use the fileName (for example, "MiImagen.jpg") to hash it and retrieve the file with that hash. Maybe we can think of a workaround for this, but I'm not sure.

Still, the collisions from 3) are the least important of the three things you said

**Comment by AxelCB** [comment]
Even though we may not be using this, it should be ready now

**Pull request closed without merging**
