### PR TITLE
Frontend Authentication. Fixes #26

### LINKED ISSUE #26: Add login or authentication to Frontend
Should think of a simple way to provide authentication in the frontend functionality so only admins can use it.

### PR DESCRIPTION
**Pull request by AxelCB**
Added authentication to frontend. It requires some steps to setup, which I'll detail below. Also, this currently affects all backend services (even those not used from the frontend). We could take advantage of this and create a valid token for all services that use our component, or add an exception on the interceptor to only validate authentication with requests from the frontend.

The steps required to make it work are:

1. Insert manually an empty user ( just username and id with the sequence, without password).
2. Try to login with that user and the desired password, so that the backend prints the hashed password to be stored in the database in its console.
3. Update the previously created user with the hashed password from before.

### CODE REVIEW

**Review by mokocchi — DISMISSED** [review]
Well done! (it works!)  
Maybe add an error message on a failed login (one error for both user not found / wrong password cases) once the password is saved. I don't know if you can tell which one is or if it's safe to show that message anyway.
Yes, the other services should use tokens too. How do you do that? It's fine to just create an user+password pair for each one?

**Comment by AxelCB** [comment]
I'll add a message when failed login, and globally, if your session expires.

There are two ways of re-using this token/auth services with the services exposed to the other components:

1. Generate the tokens beforehand and inject it (hard-coded style) in the TokenAuthenticationService.
2. Generate the users with their passwords and require the other components to handle the login/relogin logic (like re-login when session expired)

**Comment by mokocchi** [comment]
Since we are not responsible for any of the other modules let's just explain that in the documentation.
The token part it's already complete to me.

**Review by mokocchi — APPROVED** [review]
Checked.

**Pull request merged**
